TEKRAR

In [ ]:
"""
1) A array = 2 boyutlu bir tane array -> (3,5)
2) B array = 1 boyutlu bir tane array -> (15,)
3) B array'ini (3,5) olacak sekilde reshape yapalim
4) C = A + B
5) D=linspace ve E=arange ile (3,5) lik matrisler olusturalim.
6) F = D + E
7) C'nin ve F'nin her bir elemanini for dongusu ile eleman eleman carpip G = (15,1) boyutunda elde edelim.
8) C ve F'yi (15,1) sonrasında C'nin ilk elemani ile F'nin son elemani toplayarak ilerleyelim.
9) toplam degerleri eger 1 den buyukse G1 isimli bir listeye atalim, else ise G2 isimli listeye atalim
"""

In [8]:
import numpy as np
A=np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
#A = np.random.rand(3, 5)
B=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])

B1=np.arange(15)
B2=np.random.rand(15,)
print(f" {B} {B1} {B2}")

 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15] [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14] [0.87100005 0.19346282 0.72021777 0.78906991 0.24578037 0.80924278
 0.60404165 0.91207999 0.82154867 0.25263041 0.7651888  0.91700762
 0.6394371  0.45781166 0.55886251]


In [11]:
B=B.reshape(3,5)

In [13]:
C= A+B
C

array([[ 2,  4,  6,  8, 10],
       [ 7,  9, 11, 13, 15],
       [12, 14, 16, 18, 20]])

In [15]:
D=np.linspace(1,15,15).reshape(3,5)
E=np.arange(15).reshape(3,5)
#E=np.arange(10,160,10).reshape(3,5)
F=D+E
print(F)

[[ 1.  3.  5.  7.  9.]
 [11. 13. 15. 17. 19.]
 [21. 23. 25. 27. 29.]]


In [29]:
G=[]
for i in range (C.shape[0]):
    for j in range (F.shape[1]):
        res= C[i,j]*F[i,j]
        G.append(res)
print("G shape: ",np.array(G).shape)

    

G shape:  (15,)


In [42]:
C=C.reshape(15,)
F=F.reshape(15,)
G1=[]
G2=[]
F=F[::-1]
[G1.append(C[i] + F[i]) if (C[i] + F[i]) > 1 else G2.append(C[i] + F[i]) for i in range(C.shape[0])]
print(G1)
print(G2)




[np.float64(3.0), np.float64(7.0), np.float64(11.0), np.float64(15.0), np.float64(19.0), np.float64(18.0), np.float64(22.0), np.float64(26.0), np.float64(30.0), np.float64(34.0), np.float64(33.0), np.float64(37.0), np.float64(41.0), np.float64(45.0), np.float64(49.0)]
[]


In [ ]:
C_flat = C.reshape(-1, 1)  # -1 otomatik olarak 15 elemanı kullanır
F_flat = F.reshape(-1, 1)

# G1 ve G2 listelerini tanımlama
G1 = []
G2 = []

# C'nin ilk elemanı ve F'nin son elemanı toplama işlemi ile ilerleme
for i in range(len(C_flat)):  # C_flat'in uzunluğunu kullanarak döngüyü oluştur
    toplam = C_flat[i, 0] + F_flat[len(F_flat) - 1 - i, 0]  # len kullanarak sondan eleman al
    if toplam > 1:
        G1.append(toplam)
    else:
        G2.append(toplam)
# Sonuçları yazdırma
print("G1 (Toplam > 1 olanlar):", G1)
print("G2 (Toplam <= 1 olanlar):", G2)

In [ ]:
"""
[1,2,3]

[4,5,6]
7,7,7
"""
C = C.reshape(15,1)
F = F.reshape(15,1)
F =F[::-1]
G1 = []
G2 = []
for i in range(len(C)):
    toplam = C[i] + F[i]
    if toplam > 1:
        G1.append(toplam)
    else:
        G2.append(toplam)
print(G1,G2)