Numpy

In [4]:
import numpy as np
#create numpy array
liste=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
dizi=np.array(liste)
dizi



array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [5]:
#array boyutu
dizi.size
dizi.shape # (15,) 15x1 lik bir vektör //tek boyutlu


(15,)

In [10]:
#15x1 lik bir arraqyi 3x5 lik bir matrise çevirelim
dizi2 =dizi.reshape(3,5)
dizi3 =dizi.reshape(5,3)
print(dizi2)
print(dizi3)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [13]:
print(f"shape: {dizi2.shape}") # 3 x 5
print("dimension:" ,dizi2.ndim) # boyut sayısı
print("size", dizi2.size) # dizinin içerisinde kaç eleman var
print(type(dizi2))

shape: (3, 5)
dimension: 2
size 15
<class 'numpy.ndarray'>


In [15]:
dizi2D=np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]])
print(dizi2D)
print(dizi2D.ndim)
print(dizi2D.shape)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
2
(6, 4)


In [ ]:
sifir_dizi=np.zeros((3,4)) #sıfırlardan oluşan bir array
sifir_dizi


In [ ]:
#birlerden oluşan array
bir_dizi=np.ones((3,4))
bir_dizi

In [ ]:
#boş bir array oluşturma
bos_dizi=np.empty((2,4)) # pc için boş bir değer diye bir şey yoktur, boş bir array için bile 0lardan oluşan bir matris oluşturması gerekir
bos_dizi

ARANGE (basamak büyüklüğünde artarak ilerler)

In [27]:
#arange(x,y,basamak) x den başlar y (y dahil değil) ye kadar gider basamak büyüklüğünde artarak gider
#10,50,basamak=5
dizi_aralik=np.arange(10,50,10)    # size -> 4 
dizi_aralik.reshape(dizi_aralik.size,1)


array([[10],
       [20],
       [30],
       [40]])

LINSPACE ( basamak kadar sayıya böler)

In [31]:
#linspace (x,y,basamak) x ve y aralıgında (y dahil) basamak kadar sayıya böler //bu bir vektör
dizi_bosluk=np.linspace(10,50,10)
print(dizi_bosluk)
len(dizi_bosluk)

[10.         14.44444444 18.88888889 23.33333333 27.77777778 32.22222222
 36.66666667 41.11111111 45.55555556 50.        ]


10

Numpy temel operasyonları

In [32]:
a =np.array([1,2,3])
b=np.array([4,5,6])

In [33]:
print(f"toplama {a+b}")
print(f"çikarma {a-b}")
print(f"dizinin kendisiyle çarpimi {a**2}")

toplama [5 7 9]
çikarma [-3 -3 -3]
dizinin kendisiyle çarpimi [1 4 9]


In [36]:
#filtreleme
a=np.array([1,2,3])
filtre1= a>3
filtre=a<2
print(filtre)
print(filtre1)

[ True False False]
[False False False]


In [ ]:
#matris carpimi
a =np.array([[1,2,3],[4,5,6]]) #2 x 3 
b=np.array([[4,5,6],[1,2,3]]) #2 x 3 -> T -> 3 x 2 
print(a.dot(b.T))
print(a@b.T)

In [37]:
print(a.max())
print(np.max(a))

3
3


In [38]:
print(a.min())
print(np.min(a))

1
1


In [39]:
a =np.array([[1,2,3],[4,5,6]]) #2 x 3 
print(sum(a))
print(np.sum(a))

[5 7 9]
21


In [40]:
#satır satır , sütun sütun toplama
print(a.sum(axis=1) )##axis =1 satır demek
print(a.sum(axis=0 ))##axis =0 sütun demek

[ 6 15]
[5 7 9]


In [41]:
#kare kökü
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [42]:
#karesi 
print(np.square(a))
print(a**2)

[[ 1  4  9]
 [16 25 36]]
[[ 1  4  9]
 [16 25 36]]


In [46]:
#rastgele sayı üretme
rastgele_dizi=np.random.random((3,3)) # normal dagılıma göre oluşturur 0-1 
rastgele_dizi_1=np.random.rand(3,3)

print(rastgele_dizi_1)
print(rastgele_dizi)

[[0.15039721 0.88497312 0.12413835]
 [0.09829958 0.11446492 0.56275328]
 [0.64207336 0.76668976 0.48946656]]
[[0.30331802 0.90130438 0.23458379]
 [0.87270536 0.28302014 0.2342565 ]
 [0.62455186 0.65506328 0.26937694]]


In [51]:
#rastgele sayı üretme
rastgele_dizi_1=np.random.normal(0,1,5) # normal dagılıma göre 0 ortalamalı 1 standart sapmalı, 5 adet değer üret
rastgele_dizi_2=np.random.normal(0,1,(5,3))

rastgele_dizi_1.reshape(1,5)
print(rastgele_dizi_1)
print(rastgele_dizi_2)

[ 1.25424701  0.66306478 -0.21526266 -0.8341678  -0.5952026 ]
[[ 1.11382832  0.75385111 -1.36500181]
 [ 0.29791071  0.61624266 -1.00984022]
 [ 0.60065235  0.273421   -0.57068811]
 [ 0.14462193 -1.00296602 -1.42796816]
 [ 0.2056552  -0.41922662  0.36511577]]


İndeskleme ve slicing

In [52]:

dizi=np.array([1,2,3,4,5,6,7])
print(dizi[0])
print(dizi[3])
print(dizi[0:4])
print(dizi[::-1]) # reverse
print(dizi[::])


1
4
[1 2 3 4]
[7 6 5 4 3 2 1]
[1 2 3 4 5 6 7]


In [57]:
dizi2D=np.array([[1,2,3,4,5],[6,7,8,9,10]])
dizi2D

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [58]:
print(dizi2D[0,0]) # sıfırıncı satır sıfırıncı sütun
print(dizi2D[1,2])

1
8


In [59]:
print(dizi2D[1:])
print(dizi2D[1,])

[[ 6  7  8  9 10]]
[ 6  7  8  9 10]


In [60]:
dizi2D[:,2]

array([3, 8])

In [61]:
dizi2D[:,2:4]

array([[3, 4],
       [8, 9]])

In [63]:
dizi2D[[0,1], [1,3]]

array([2, 9])

In [62]:
dizi2D[-1,:]

array([ 6,  7,  8,  9, 10])

shape manipulation

In [64]:
dizi2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
dizi2D_shape=dizi2D.shape
dizi2D_shape

(3, 3)

In [65]:
dizi2D.reshape(9,1)
dizi2D.reshape(dizi2D_shape[0]*dizi2D_shape[1],1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [66]:
dizi2D.reshape(dizi2D_shape[0]*dizi2D_shape[1],-1) # -1 yazarsan kendi hesaplar

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [67]:
dizi2D.ravel() #tensorflow -> flatter 

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
dizi2D.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [74]:
a1 =np.array([[1,2,3],[4,5,6],[7,8,9],[4,5,6],[7,8,9]]).T #2 x 3 
a2 =np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]).T #2 x 3 
print(a1.shape)
print(a2.shape)
print(a1)


(3, 5)
(5, 3)
[[1 4 7 4 7]
 [2 5 8 5 8]
 [3 6 9 6 9]]


In [121]:
b =np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]) #2 x 3 
b.shape      
b=b.reshape(3,5)
C=a.T+b
print(C)

[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]]


In [155]:

E=np.arange(15).reshape(3,5)
D=np.linspace(1,16,15).reshape(3,5)
F=D+E
F


 


array([[ 1.        ,  3.07142857,  5.14285714,  7.21428571,  9.28571429],
       [11.35714286, 13.42857143, 15.5       , 17.57142857, 19.64285714],
       [21.71428571, 23.78571429, 25.85714286, 27.92857143, 30.        ]])

In [161]:
G=[]

for i in range(C.shape[0]):
  for j in range(C.shape[1]):
       G.append(C[i,j]*F[i,j] )
print(np.array(G).shape)

(15,)


In [163]:
C=C.reshape(15)
F=F.reshape(15)
print(C)
print(F)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]
[ 1.          3.07142857  5.14285714  7.21428571  9.28571429 11.35714286
 13.42857143 15.5        17.57142857 19.64285714 21.71428571 23.78571429
 25.85714286 27.92857143 30.        ]


In [171]:
C=C.reshape(15)
F=F.reshape(15)
G1=[]
G2=[]
for i in range(C.shape[0]):
       res= C[i-1]+F[-i]
       print(C[i-1])
       print(F[-i])
       if res>1:
              G1.append(res)
       else:
             G2.append(res)

print(G1)
print(G2)
print()

30
1.0
2
30.0
4
27.92857142857143
6
25.857142857142858
8
23.785714285714285
10
21.714285714285715
12
19.642857142857142
14
17.57142857142857
16
15.5
18
13.428571428571429
20
11.357142857142858
22
9.285714285714285
24
7.214285714285714
26
5.142857142857142
28
3.071428571428571
[np.float64(31.0), np.float64(32.0), np.float64(31.92857142857143), np.float64(31.857142857142858), np.float64(31.785714285714285), np.float64(31.714285714285715), np.float64(31.642857142857142), np.float64(31.57142857142857), np.float64(31.5), np.float64(31.42857142857143), np.float64(31.357142857142858), np.float64(31.285714285714285), np.float64(31.214285714285715), np.float64(31.142857142857142), np.float64(31.07142857142857)]
[]

