<a href="https://colab.research.google.com/github/damildot/pupilica_AI_bootcamp/blob/main/numpy_stacking.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
Stacking

In [1]:
import numpy as np

In [2]:
dizi1=np.array([1,2,3,4])
dizi2=np.array([5,6,7,8])

In [3]:
np.vstack((dizi1,dizi2))


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
np.hstack((dizi1,dizi2))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
np.stack((dizi1,dizi2),axis=1)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [11]:
#problem tanımı: 2 boyutlu (2 satır ve 2 sütun) 3 adet array oluştur,
#bunları yatayda ve dikeyde birleştir
dizi1=np.array([[1,2],[3,4]])
dizi2=np.array([[5,6],[7,8]])
dizi3=np.array([[9,10],[11,12]])
print(np.vstack((dizi1,dizi2,dizi3)))
print(np.hstack((dizi1,dizi2,dizi3)))

array([[ 1,  2,  5,  6,  9, 10],
       [ 3,  4,  7,  8, 11, 12]])